### ISSUE TITLE
Manual para escanear un proyecto

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#10]
Hablar de los ficheros de configuración dependiendo del lenguaje
Comprobar la ejecución de Test Interesante un video tutorial [ActivePresenter en Windows](http://atomisystems.com/download/)

[revclopezno anexo-manual.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/12/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1463566776.86/12/revclopezno_anexo-manual-usuario.pdf)

[anexo-manual.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/12/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1462349564.75/12/anexo-manual-usuario.pdf)

**Comment by albartolome** [comment]
attached anexo-manual-usuario.pdf
Corregidos fallos en el manual de usuario en el que se explica como realizar análisis de proyectos con los distintos scanner de SonarQube

**Comment by albartolome** [comment]
attached revclopezno_anexo-manual-usuario.pdf
Adjunto revisión con comentarios pdf

**Comment by albartolome** [comment]
He probado los manuales de usuario referentes a SonarQube Scanner y SonarQube Scanner for MSBuild y siguiendo sus pasos he conseguido escanear los proyectos de la primera convocatoria (PHP. Java y C#). He dejado los resultados en la instancia de SonnarQube.
Creo que es la mejor forma de probar la calidad de tu documentación ;-)
