### ISSUE TITLE
Crear anexo manual del administrador

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#13]
Crear un manual del administrador con la parte de instalación y despliegue de la instancia de SonarQube, descrita en el manual de usuario. Incluir una descripción de las configuraciones realizadas.
[anexo-manual-administrador.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/16/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1462349466.39/16/anexo-maunal-administrador.pdf)

**Comment by albartolome** [comment]
attached anexo-maunal-administrador.pdf
Creado el anexo Manual del Administrador en el que se explica como configurar los ficheros de SonarQube y desplegar la instancia en la plataforma OpenShift
