### ISSUE TITLE
Incorporar nuevos proyectos en la instancia de SonarQube

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#15]
Incluir análisis de más trabajos fin de grado en la [instancia](http://tfgqa-ubugii.rhcloud.com/) de SonarQube. Incluir además proyectos presentados en la primera convocatoria 2016.

**Comment by albartolome** [comment]
Incorporados los siguientes proyectos:
    Estimación de biomasaforestal a partir de imágenes aéreas y LIDAR.
    UBUGRAPH 4.0
    Aplicación Fitness para Android
    EasyBot para Android
    Filmoteca Android
    Sistema de estimación de edad a partir de radiografías dentales
    Resolución Puzzle Android
    Chameleon Sensor 1.0
Se han re-escaneado los demás proyectos para incluir la fecha de presentación en el nombre de los mismos.
