### ISSUE TITLE
Conceptos téoricos

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#17]
Calidad del software
    Medidas de código
Utilizar referencia Medición para la gestión en la ingeniería del software
Autor: José Javier Dolado Cosín; Luis Fernández Sanz Editorial: Madrid : RA-MA, ©2000. Edición/Formato: Print book : Español (spa)Ver todas las ediciones y todos los formatos Base de datos: WorldCat

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/9/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1459939926.75/9/revclopeznomemoria_conceptos_teoricos.pdf

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/9/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1459784881.78/9/memoria_conceptos_teoricos.pdf

**Comment by mbm0089** [comment]
attached [memoria_conceptos_teoricos.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/9/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1459784881.78/9/memoria_conceptos_teoricos.pdf)
Adjunto una versión provisional del apartado Conceptos Teóricos. Me he basado en tres libros diferentes para elaborar este apartado:
Libro Medición para la Gestión en la Ingeniería del Software que me has sugerido
Libro Software Engineering 9ª Edición - Sommerville
Libro Software Engineering: A practitioner's approach - Pressman
Me gustaría revisar este apartado en el proximo sprint porque me da la sensación de que no lo estoy haciendo bien.
