### ISSUE TITLE
Apartado Aspectos relevantes del desarrollo del proyecto

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#18]
Crear la documentación correspondiente al apartado Aspectos Relevantes del Desarrollo del Proyecto
[memoria_aspectos_relevantes.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/24/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467618541.4/24/memoria_aspectos_relevantes_v2.0.pdf)
[memoria_aspectos_relevantes.pdf](
https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/24/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467368461.78/24/memoria_aspectos_relevantes.pdf)

**Comment by albartolome** [comment]
attached memoria_aspectos_relevantes.pdf
Adjunto una versión provisional del apartado; a consultar con el tutor
