### ISSUE TITLE
Apartado Conclusiones y Líneas de trabajo futuras del desarrollo del proyecto

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#20]
Crear la documentación correspondiente al apartado Conclusiones y Líneas de trabajo futuras del proyecto.
[memoria_Trabajos_futuros.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/26/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467618394.97/26/memoria_trabajos_futuros.pdf)

**Comment by albartolome** [comment]
attached memoria_trabajos_futuros.pdf
Adjunto la documentación correspondiente al apartado.
