### ISSUE TITLE
Escaneo del histórico de versiones de un TFG

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#21]
Posibles candidatos PLQUIZ Gestor de trabajos fin de grado y/o máster.

**Comment by mbm0089** [comment]
Creado el escaneo del histórico de versiones para los proyectos propuestos. Los resultados se pueden ver en los siguientes enlaces:

- Gestor de trabajos fin de grado y/o máster: http://tfgqa-ubugii.rhcloud.com/overview?id=tfg.gestor.trabajos
- PLQuiz: http://tfgqa-ubugii.rhcloud.com/overview?id=es.ubu.inf.tfg%3APLQuiz
