### ISSUE TITLE
Crear trabajos relacionados de la memoria

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#22]
Comparar a nivel funcional con OpenHub https://www.openhub.net/ Añadir una tabla comparativa.

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/15/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467749616.84/15/memoria_trabajos_relacionados.pdf

**Comment by mbm0089** [comment]
Adjunto el apartado Trabajos Relacionados de la memoria
[memoria_trabajos_relacionados.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/15/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467749616.84/15/memoria_trabajos_relacionados.pdf)
