### ISSUE TITLE
Apéndice B: Especificación de Requisitos

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#26]
Crear la documentación correspondiente al apéndice Especificación de Requisitos.

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/27/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467619413.67/27/anexos_especificacion_requisitos.pdf

**Comment by mbm0089** [comment]
Adjunto la documentación correspondiente al apéndice Especificación de Requisitos
[anexos_espec_requisitos.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/27/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467619413.67/27/anexos_especificacion_requisitos.pdf)
