### ISSUE TITLE
Apéndice A: Plan de proyecto

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#27]
Crear la documentación correspondiente al apéndice Plan de Proyecto.

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/25/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467883318.35/25/anexo_plan_proyecto.pdf

**Comment by mbm0089** [comment]
Adjunto el apartado correspondiente al Plan de Proyecto
[anexo_plan_proyecto.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/25/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1467883318.35/25/anexo_plan_proyecto.pdf)
