### ISSUE TITLE
Sprint.1

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#30]
Se han finalizado y cerrado las issue #1 #2 #6 #12 #17

**Comment by mbm0089** [comment]
Issue #1 : Documentación comprendida y prácticas realizadas.

**Comment by mbm0089** [comment]
Issue #2 : Conseguida referencia bibliográfica adecuada. Se estudia y comprende.

**Comment by albartolome** [comment]
Issue #12 Documentación añadida y practica completada.

**Comment by mbm0089** [comment]
Issue #3 : Leído y comprendida documentación sobre BitBucket.

**Comment by albartolome** [comment]
Issue #17 Asimilados conceptos teoricos listos para incluir en la practica.

**Comment by mbm0089** [comment]
Comenzar a trabajar en #3 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #8 @mbm0089

**Comment by mbm0089** [comment]
Comenzar a trabajar en #4 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #5 @albartolome

**Comment by clopezno** [comment]
Para representar el concepto de sprint en Github es mejor asociarlo a un hito. Cuando una tarea/historia se prolonga en el tiempo  y se divide en más tareas es el concepto de épica que se indica en Github.

De todas formas el hecho de dar esta solución con los conocimientos que os he explicado en la asignatura lo valoro positivamente.
