### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#31]
Se han finalizado y cerrado las issue #4 #5 #3 #8

**Comment by mbm0089** [comment]
Issue #4 : Se ha creado la documentación necesaria.

**Comment by mbm0089** [comment]
Issue #5 : 
- Se instalan las dependencias necesarias para OpenShift. 
- Se modifican las versiones necesarias de JWS, Ruby y Git

**Comment by albartolome** [comment]
Issue #3 Ya se ha hecho un despliegue de una instancia local de la herramienta SonarQube.

**Comment by albartolome** [comment]
Issue #8 Analizados los proyectos:
Proyecto en Java
Proyecto en PHP
Proyecto en Python
Proyecto Maven / Ant
Proyecto desde un repositorio público (GitHub, Bitbucket, XP-Dev, etc.)

**Comment by mbm0089** [comment]
Empezar a trabajar en #10 @albartolome

**Comment by albartolome** [comment]
Empezar a trabajar en #14 @mbm0089

**Comment by mbm0089** [comment]
Empezar a trabajar en #15 @albartolome

**Comment by albartolome** [comment]
Empezar a trabajar en #21 @mbm0089
