### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#32]
Se han finalizado y cerrado las issue #10 #21 #15 #14

**Comment by albartolome** [comment]
Issue #10 Manual leido, corregido y compendido.

**Comment by mbm0089** [comment]
Issue #21 Creado el escaneo del histórico de versiones para los proyectos propuestos.

**Comment by albartolome** [comment]
Issue #15 Se han añadido los siguiente proyectos:
Estimación de biomasaforestal a partir de imágenes aéreas y LIDAR.
UBUGRAPH 4.0
Aplicación Fitness para Android
EasyBot para Android
Filmoteca Android
Sistema de estimación de edad a partir de radiografías dentales
Resolución Puzzle Android
Chameleon Sensor 1.0
Se han re-escaneado los demás proyectos para incluir la fecha de presentación en el nombre de los mismos.

**Comment by mbm0089** [comment]
Issue #14 Realizada prueba de ejemplo en SonarQube

**Comment by mbm0089** [comment]
Empezar a trabajar en #22 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #13 @mbm0089

**Comment by mbm0089** [comment]
Empezar a trabajar en #24 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #7 @mbm0089
