### ISSUE TITLE
Sprint 4.

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#33]
Se han finalizado y cerrado las issue #22 #24 #13 y #7

**Comment by albartolome** [comment]
Issue #13 creado el correspondiente anexo.

**Comment by albartolome** [comment]
Issue #7  Documentacion sobre Técnicas y Herramientas de la memoria añadida.

**Comment by mbm0089** [comment]
Issue #24 Creada tabla comparativa de diferencias funcionales

**Comment by mbm0089** [comment]
Issue #24 Instalado y configurado widget en plataforma de evaluación de TFG

**Comment by mbm0089** [comment]
Empezar a trabajar en #16 @albartolome

**Comment by mbm0089** [comment]
Empezar a trabajar en #20 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #9 @mbm0089

**Comment by albartolome** [comment]
Comenzar a trabajar en #18 @mbm0089
