### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#34]
Se dan por resueltas las tareas #9 #16 #18  y #20

**Comment by albartolome** [comment]
Issue #9 Manual de instalación de SonarQube añadido y documentado.

**Comment by albartolome** [comment]
Issue #18 Apartado Aspectos relevantes del desarrollo del proyecto correctamente añadido.

**Comment by mbm0089** [comment]
Issue #16  Se generan los screen-cast

**Comment by mbm0089** [comment]
Issue #20 Creada documentación

**Comment by mbm0089** [comment]
Empezar a trabajar en #26 @albartolome

**Comment by mbm0089** [comment]
Empezar a trabajar en #27 @albartolome

**Comment by albartolome** [comment]
Comenzar a trabajar en #19 @mbm0089

**Comment by albartolome** [comment]
Comenzar a trabajar en #25 @mbm0089
