### ISSUE TITLE
Sprint 6.

### ISSUE THREAD

**Issue by albartolome** [albartolome/GESPRO_GESTIONTAREAS#35]
Se han finalizado y cerrado las issue #19 #25 #26 #27

**Comment by albartolome** [comment]
Issue #19 cargado proyecto PHP - Java - C# - JavaScript y añadido correctamente.

**Comment by mbm0089** [comment]
Issue #27 Se ha creado la documentación del proyecto

**Comment by albartolome** [comment]
Issue #25 Se ha calculado la información estadística y se ha configurado un Quality Gate para SonarQube.

**Comment by mbm0089** [comment]
Issue #26 Añadido anexo B con especificación de requisitos
