### ISSUE TITLE
Elaboración de la documentación sobre el proyecto

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#4]
Elaboración de los apartados 1. Introducción y 2. Objetivos de la memoria del proyecto utilizando LaTeX y la plantilla proporcionada para el TFG.

**Comment by albartolome** [comment]
attached REV01_SonarQube_memoria.pdf
Adjunto la revisión de la memoria en un documento pdf con comentarios.

**Comment by albartolome** [comment]
attached BiblioCalidad.bib
Referencias bibliográfica en bibtex
