### ISSUE TITLE
Despliegue de instancia remota de SonarQube

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#5]
Despliegue de una instancia remota de la herramienta SonarQube en la plataforma de OpenShift. Para el despliegue se utilizarán las herramientas de cliente que proporciona OpenShift (ver [enlace](https://developers.openshift.com/en/managing-client-tools.html)).

**Comment by albartolome** [comment]
Para poder instalar las herramientas de OpenShift (rhc) en Windows, previamente ha sido necesario instalar Ruby y Git, tal y como se indica en esta guía. Según la guía deben instalar las últimas versiones disponibles tanto de Ruby(http://rubyinstaller.org/), como de Git(https://git-scm.com/). Sin embargo, al instalar las últimas versiones, se producían los siguientes errores en el funcionamiento de las herramientas rhc:
    Tras instalar rhc (comando gem install rhc), se producía error cuando se intentaba configurar las herramientas con el comando rhc setup. Este error se ha solucionando probando versiones anteriores de Ruby.
    Durante la configuración de rhc se producía un aviso, indicando que no ha sido posible verificar la instalación de Git. Sin embargo, Git se encontraba instalado en la máquina. Este problema no permitía clonar automaticamente el repositorio de la aplicación después de crearla con el comando rhc app-create. También, debido a que rhc no localizaba la instalación de Git, no era posible acceder de forma remota a la aplicación mediante ssh (comando rhc ssh <nombre_app>).
Después de buscar soluciones a estos problemas, aparentemente comunes, en diversos foros y sin encontrar una solución particular, se ha decidido utilizar las versiones de Ruby y Git especificadas en la guía arriba indicada.
Utilizando estas versiones se han podido solucionar los problemas anteriores:
    Ruby 1.9.3-p550: http://rubyinstaller.org/downloads/archives
    Git 1.9.4: https://github.com/msysgit/msysgit/releases/tag/Git-1.9.4-preview20140929

**Comment by albartolome** [comment]
Despues de crear una aplicación DIY en OpenShift e instalar SonarQube, se ha producido el siguiente error al lanzar la instancia del servidor de SonarQube: "unable to bind listener to any port in the range 32000-32999. (Permission denied)".
Este error se debe a que SonarQube utiliza Java Wrapper Service, el cual enlaza con puertos sobre los que la plataforma OpenShift no concede permisos. En este artículo se explica la causa del problema más detalladamente, así como la solución al mismo.
En resumen, el problema se soluciona sustituyendo las librerías de JWS (versión 3.2.3) que utiliza SonarQube, por una versión más reciente, en la que se incluye la propiedad wrapper.backend.type. Esta propiedad, con el valor "PIPE", soluciona el problema anterior.
La versión de JWS utilizada en este caso está disponible en http://wrapper.tanukisoftware.com/download/3.5.9/wrapper-delta-pack-3.5.9.tar.gz

**Comment by albartolome** [comment]
Instancia de SonarQube desplegada - URL: http://sonarqube-ubu.rhcloud.com/
