### ISSUE TITLE
Documentación sobre técnicas y herramientas

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#7]
Indicar una visión general de la herramienta. Descripción funcional breve. Para qué se utiliza en la herramienta en el proyecto y referenciar a Web o libro.
SonarQube OpenShift
Jira Issues
Git IntelliJ Java LateX ....

**Comment by albartolome** [comment]
attached memoria_tecnicas_herramientas.pdf
Adjunto una versión provisional del apartado Técnicas y Herramientas de la memoria.

**Comment by albartolome** [comment]
attached clopezno_memoria_tecnicas_herramientas.pdf
Adjunto una revisión con comentarios sobre el pdf.
