### ISSUE TITLE
Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by mbm0089** [albartolome/GESPRO_GESTIONTAREAS#9]
Anexo de la memoria En Open shift En Local

[RevPlammenManual Usuario](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/11/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1461154209.51/11/RevPlammenManual%20de%20usuario.pdf)

[Manual de usuario.pdf](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/11/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1461078026.03/11/Manual%20de%20usuario.pdf)

**Comment by albartolome** [comment]
attached Manual de usuario.pdf

https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues/attachments/11/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/1461078026.03/11/Manual%20de%20usuario.pdf

Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

**Comment by albartolome** [comment]
attached RevPlammenManual de usuario.pdf
Revisión de manual de usuario. Complementarla con la entregada en papel.
